language: ruby

cache:
  - bundler

rvm:
  - 2.6.1

script:
  - docker build . -t dshivang0/photoapp_api:latest
  # - docker run -e RAILS_ENV=production -e DB_USER_PASSWORD=$DB_USER_PASSWORD -e DB_NAME=$DB_NAME -e DB_USER_NAME=$DB_USER_NAME -e SUPER_SECRET_AUTH_KEY=$SUPER_SECRET_AUTH_KEY -e SUPER_SECRET_USER_KEY=$SUPER_SECRET_USER_KEY dshivang0/photoapp_api rspec
  - docker run -e DB_USER_PASSWORD=$DB_USER_PASSWORD -e DB_NAME=$DB_NAME -e DB_USER_NAME=$DB_USER_NAME -e DB_USER_PASSWORD_ALT=$DB_USER_PASSWORD_ALT -e DB_NAME_ALT=$DB_NAME_ALT -e DB_USER_NAME_ALT=$DB_USER_NAME_ALT -e SUPER_SECRET_AUTH_KEY=$SUPER_SECRET_AUTH_KEY -e SUPER_SECRET_USER_KEY=$SUPER_SECRET_USER_KEY -e RAILS_ENV=$RAILS_ENV dshivang0/photoapp_api:latest rspec
  # - docker run -p 80:3000 dshivang0/photoapp_api:latest 

env:
  global:
  - DB_NAME = 'daajhd2ooii697'
  - DB_USER_NAME = 'juirxazhueljgn'
  - DB_USER_PASSWORD = 'c95514566f95516d0a5515a97980563dd9704797bffeb19c5028415140556ebe'
  - DB_NAME_ALT = 'dbthdorlp3nnpk'
  - DB_USER_NAME_ALT = 'cbsxigslafhwrl'
  - DB_USER_PASSWORD_ALT = 'abc0e4337e73f0e7e3cfc9055c3fae4120224b2a30668a65cd1f52bfe15af8de'
  - secure: XP89nl2pTeFPtPXijv68P8QWVDB50QtbecUT+jNYVqgGDup3TuzJsm83qDOoWsUqeXGXW0vH/wY/Hi1QCFDTDngdDxMcFH4ZkuxMVhkoJrFD24EzXrkWIdGAWVb9lz4doQgPjjHLgeRg5MiPUHOe2rzzPG9WLYV428c37c5+sxszr8NAGEx7Is5G9f8H29ofFKebb+9Yi4EQaImdXIso7tguWAzC1UM5bg+wS9Lb7bf5iKTh5dTUiBuwyPeHMMoSE2m1iJNndldVVlRxSGTlapWdLjzsEue7HupyLAgiEqeXFqElXnfqW3+6B9ErRJB3DxU7LKi+jfd43LVgebO17vMZZNlw5e/G2e0EmfWP5cSEksS9irHfrD7Yp7ubI/sG4O+OLysEXasguaXnsaLBnGfTBI38pM8FkoWPdK6+T2t9jYQkTyAk6AE3QAh8bHpI3aGpDt/KoLc4lX7gkgjrsoRrKgzBr+2AWFCoOhT4WzgbAlGV3NzufwIJb7gjtFYAcjtHBs/9IA5Rq96aF4DGK318+dOm8w4MroaMBFMIg1NMLpLYOGjU7HPQio2lAwUH0Guh5nMv6B7n5qeSO0qyORjKCOdMvjzP7vYCprmgHrtUnQueGxPl2AC2LDY70cP9hny7ZyjFYZR/Z6D/4npCeNbGpzB+YG0xguV3WLmjaIg=
  - secure: x5O0PODI8a+ZdiV1IPP9RG0aTinFOK6274/KsBG+aE1/wtENFuRQIyaIocdGPFDG9jx4epjE59Dwtks/o+m3XxYoPeQ+tt+Qr2Z1N+6PKtRsq5huix11mXKLWmNWnG1DcBMhXedAt72yrgV9fc7I7nMU2yJb72bOQCAjb5nhqugw0eWKPgicbUtau4CD01zLXToDomkgizRv+ENX9I4trW9g3PSoPWH6ir1S+LV/KvhYrYLAeXkz1kRY36SBu5xslWS7o6asyQOAV/xfW8R5wrS5dHy+8CLztxzzNljPXkiaCPx3qQMQlg+cQc4GuUbaWYD8v/lyFwXriaFXVhlcal6mDohdX2p4zdaeh0JdOIAC7VN9Nc76jMJWI5VsJvr9tcCYGixb3+vVdRqaPVDWKx0SdXbf6BTQ2OE52cV+lps1PlrHTHWO9tWWfsru37VC3sHx1XsWOQBsG7AYDMInjt5QnPu5wkvd9XpPcNNwEiIVKb3ZF/1NxS8gImTUmYOgEq5zdrLeAwfhJXRiIaCNBCC8N/tB3yUmmyv0dIXSNxoQEZf58HUEaXCx3a2yLZ75i6T6D7NE+LT34aVRslhWXJUii406mQE3ta2YzA6KPxSrtnUH7nHxBz5KhMjVEprS3UrLQB+5DriYDAS6o+MptAJA+CO7lV9fTCeMobulXXs=
  - secure: "ZB2Z9fDturnqMIIKQIe/4gX5IHgpSLF/Gmx3TbbutYG96znxmeaMZKngsFrOeWIzvpvNXB5sWqX8Mekr82/GBgAScfNWkhqWKO9HKbUgr1GwOBJKLr2gdjjWS8XeP1+qt00enDfhv9Xi339DgYSZMzSGGaALsJ2YuTvCm2ak9QBUMJZPJLkF4SkzXYBrKY0vJcuoHvqYIORo6q8pnUaJAnKwb7CUdGy/Dje7DKqh30Agu4rHdyy9DEGsqosuoU1XqTDpegA0m4dRxsaKZuTpYyFqqUf9+/K251O6oupTmVGQ/MnLbF8Z8OOJYX9HO9ZMJFLSGJoIl/FXo9zw4+lVGS3MOZYsU0Ce0b5KsRJdzmVVIbU6MoAUt/rOKOYynOuSA6HNT3yjP2vbV9umpc7lPySp9P7bY2zMCebNcaMSSVIMkFpl5OVcz9FaQeO4QJlxWU9QmGSO0vil67fc6ZArAzodHHk4L8TzrJMh9FD+TnGezQ4KDX0bD5dYmnqbzJYzhpxZtsc7l+tP4cDgbpSkydsWChWl3hmtp+osGD7fCe2QaL859vwRCbAUjvNBqs8gb2YNtpfW77e1KPKPn7j8MvX8lUPGBy7lUlM1QcMhhUoX0ZpO2MQ9B3v0roTzj9Cs5cFkJP4DGrB8ItFilUydPfh0e59NU/QTtkw4bk5dqS8="
  # - secure: "WqFJDeZlUmP/UL6wdWDh3mLQDyuwisHI+4JFFjBBbkA6AzbGOnOfC+jDbA6dXonh4dGcq8xe0+L0rtZavvSlRFpXbJZtlRusK/oVxOhDMtoYULln9k0uAIxBq7wWSx1xWD4aOdqHq/FwzsmoeR2buK8D4YKJ+MPJctlvDid4eA1AQ23aSarWLcMSdgZJOi7XooMuI9NOl7KXknrTe353W5RFx9E0VwZ/IVEr+v+ABi8cHIZnEf/RWZK1vk9lU1Bxv2tB1weN7Oeh+AxZDvrnPfEZI51GRNTRZhAZTzOsW30nI4aoO3tyFECUEAkLEcYNia7ghya5h1I7LwAbu7BwhsVbvc3/J4pQdLFEabSaaVuGNUng4cQHvBoLTN/xbT5g4ipy5+qDadOMjjX4xCx7P5wyH7RcYLLohAI94rq9n4ZpwSKKi7hwL7WWm234UMVLNCeyaUcFMHyprm6x+d8aACBYlj8gg3zE/uG0u6VIuPw7iiWa7l2Do0rfG6OH9PKddemBl9IQvNc5asuBS51vI1H0tpnRXOjRLLF8eIZXST0V9BGJA+pZymwuO+wboPoN0ecDSYQQ+UEmDwv076efaSOLab6ZTgxcjgOI3cuxKNF0n3/kJoX5DQdNd5vygBJfJpjhm7sud/VrJe6tKNL22RiEtLgVZ86cRq96o6VHx44="

  # - SUPER_SECRET_AUTH_KEY
  # - SUPER_SECRET_USER_KEY

  # - DB_USER
  # - DB_USER_NAME
  # - DB_USER_PASSWORD

  # - DB_USER_ALT
  # - DB_USER_NAME_ALT
  # - DB_USER_PASSWORD_ALT

  # - RAILS_ENV=test
  # - RAILS_ENV=development

deploy:
  provider: heroku
  api_key:
    secure: "iwJA1noJIb5sY8vdxJ6I6H/fAM09ZvPegSlEnt/JPLYE7/7DgM86vHU24vszq+QUbR/58w6diVDlaYO+aYQmd92lkT964Z4Z7hl/0EP+sq24yt7GPUeU6sZNN+HJ80sI5YtPO3f1L7CdlhWPZhpdnykzvD0SeRDT/qvPi5TF8CQaqZH4beCQVqKaSp2fIwNhlAKupPCGpeQv3HY2dHjx9ngKr7CSJqomyI7RGDl1wB2Gm4ImrldzMSve93PHt+33PekU8WLc+VDU8Sc1N3EVUlTYEo3Ex6+nDmP3wmtoWSjNqCOPyCwRZBBvS58SL/HBuLnvwyFgKAR7+yMVNMA71KbMM1ebPNo+bY49bHSXZMe9Q5qtH5bdTK35gqWy2Kh0+Gt+yl8A+5vMT7BO/OLUYx9rjXtX+iF6bbPhsI9M7/WSZ/4E8HSmkSFXG9NUqI6qRWfl+rDp0iUFWbp8hfQlT3tLv4bMCjZZJDrxJLyF7SA5gLW4w93kLW0487PBK/weZPApk7GYkprWBM5O3AnGYHSYafktdhYx9AOL7/ld0n3KKUWm7X0aX7cD+GbNub2c+FphBBM/VxYBeFCzpdQ20GVg7QWW2hnKrc3BPe87Nb6/tc1FXKKAXGTA22YN2wyA0UxZoH2YtbHRVFwtc70AYYbfb6M+F4718gnDsDq0g8M="
  app:
    ci_cd: photoapp-api