language: ruby

cache:
  - bundler

rvm:
  - 2.6.1

script:
  - docker build . -t dshivang0/photoapp_api:latest
  - docker run dshivang0/photoapp_api rspec
  # - docker run -p 3000:3000 dshivang0/photoapp_api:latest 

env:
  global:
  - secure: XP89nl2pTeFPtPXijv68P8QWVDB50QtbecUT+jNYVqgGDup3TuzJsm83qDOoWsUqeXGXW0vH/wY/Hi1QCFDTDngdDxMcFH4ZkuxMVhkoJrFD24EzXrkWIdGAWVb9lz4doQgPjjHLgeRg5MiPUHOe2rzzPG9WLYV428c37c5+sxszr8NAGEx7Is5G9f8H29ofFKebb+9Yi4EQaImdXIso7tguWAzC1UM5bg+wS9Lb7bf5iKTh5dTUiBuwyPeHMMoSE2m1iJNndldVVlRxSGTlapWdLjzsEue7HupyLAgiEqeXFqElXnfqW3+6B9ErRJB3DxU7LKi+jfd43LVgebO17vMZZNlw5e/G2e0EmfWP5cSEksS9irHfrD7Yp7ubI/sG4O+OLysEXasguaXnsaLBnGfTBI38pM8FkoWPdK6+T2t9jYQkTyAk6AE3QAh8bHpI3aGpDt/KoLc4lX7gkgjrsoRrKgzBr+2AWFCoOhT4WzgbAlGV3NzufwIJb7gjtFYAcjtHBs/9IA5Rq96aF4DGK318+dOm8w4MroaMBFMIg1NMLpLYOGjU7HPQio2lAwUH0Guh5nMv6B7n5qeSO0qyORjKCOdMvjzP7vYCprmgHrtUnQueGxPl2AC2LDY70cP9hny7ZyjFYZR/Z6D/4npCeNbGpzB+YG0xguV3WLmjaIg=
  - secure: x5O0PODI8a+ZdiV1IPP9RG0aTinFOK6274/KsBG+aE1/wtENFuRQIyaIocdGPFDG9jx4epjE59Dwtks/o+m3XxYoPeQ+tt+Qr2Z1N+6PKtRsq5huix11mXKLWmNWnG1DcBMhXedAt72yrgV9fc7I7nMU2yJb72bOQCAjb5nhqugw0eWKPgicbUtau4CD01zLXToDomkgizRv+ENX9I4trW9g3PSoPWH6ir1S+LV/KvhYrYLAeXkz1kRY36SBu5xslWS7o6asyQOAV/xfW8R5wrS5dHy+8CLztxzzNljPXkiaCPx3qQMQlg+cQc4GuUbaWYD8v/lyFwXriaFXVhlcal6mDohdX2p4zdaeh0JdOIAC7VN9Nc76jMJWI5VsJvr9tcCYGixb3+vVdRqaPVDWKx0SdXbf6BTQ2OE52cV+lps1PlrHTHWO9tWWfsru37VC3sHx1XsWOQBsG7AYDMInjt5QnPu5wkvd9XpPcNNwEiIVKb3ZF/1NxS8gImTUmYOgEq5zdrLeAwfhJXRiIaCNBCC8N/tB3yUmmyv0dIXSNxoQEZf58HUEaXCx3a2yLZ75i6T6D7NE+LT34aVRslhWXJUii406mQE3ta2YzA6KPxSrtnUH7nHxBz5KhMjVEprS3UrLQB+5DriYDAS6o+MptAJA+CO7lV9fTCeMobulXXs=
