version: '3'

services:
  blogapi:
    image: dshivang0/photoapp_api:latest
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "80:3000"
    networks:
      - myapp

networks:
  myapp:
    driver: bridge
