# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

# 47889
production:
  adapter: postgresql
  host: 'ec2-34-234-228-127.compute-1.amazonaws.com'
  port: 5432
  encoding: unicode
  database: <%= ENV.fetch('DB_NAME') %>
  pool: 15
  username: <%= ENV.fetch('DB_USER_NAME') %>
  password: <%= ENV.fetch('DB_USER_PASSWORD') %>
  timeout: 5000

test:
  adapter: postgresql
  host: 'ec2-54-165-36-134.compute-1.amazonaws.com'
  port: 5432
  encoding: unicode
  database: <%= ENV.fetch('DB_NAME_ALT') %>
  pool: 15
  username: <%= ENV.fetch('DB_USER_NAME_ALT') %>
  password: <%= ENV.fetch('DB_USER_PASSWORD_ALT') %>
  timeout: 5000

  # 47889
development:
  adapter: postgresql
  host: 'ec2-34-234-228-127.compute-1.amazonaws.com'
  port: 5432
  encoding: unicode
  database: <%= ENV.fetch('DB_NAME') %>
  pool: 15
  username: <%= ENV.fetch('DB_USER_NAME') %>
  password: <%= ENV.fetch('DB_USER_PASSWORD') %>
  timeout: 5000

# default: &default
#   adapter: sqlite3
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

# # Warning: The database defined as "test" will be erased and
# # re-generated from your development database when you run "rake".
# # Do not set this db to the same as development or production.
# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3
